---
name: Vulnerability Scan

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  repository:
    name: Get Repository Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.repository.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Output
        id: repository
        run: echo "apps=$(yq eval-all --indent 0 --output-format json '[.]' apps/*/metadata.yaml)" >> $GITHUB_OUTPUT

  grype:
    name: Download Grype
    runs-on: ubuntu-latest
    steps:
      - name: Install Grype
        uses: anchore/scan-action/download-grype@8d2fce09422cd6037e577f4130e9b925e9a37175 # v7.3.1
        id: grype

      - name: Update Database
        run: ${{ steps.grype.outputs.cmd }} db update

      - name: Create Cache Key
        id: cache
        run: echo "key=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache Database
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

  vulnerability-scan:
    needs: ["repository", "grype"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps: ${{ fromJSON(needs.repository.outputs.apps) }}
      max-parallel: 4
      fail-fast: false
    permissions:
      security-events: write
    steps:
      - name: Retreive Cache Key
        id: cache
        run: echo "key=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Restore Database
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

      - name: Scan
        uses: anchore/scan-action@8d2fce09422cd6037e577f4130e9b925e9a37175 # v7.3.1
        id: scan
        with:
          fail-build: false
          image: ghcr.io/${{ github.repository_owner }}/${{ matrix.apps.name }}:rolling

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@439137e1b50c27ba9e2f9befc93e43091b449c34 # v3.32.0
        with:
          category: ${{ matrix.apps.name }}
          sarif_file: ${{ steps.scan.outputs.sarif }}
